### PR TITLE
👩🏽‍💻 Use TUI for a better console experience

### PR DESCRIPTION
**Pull request by 123marvin123**
This PR is a work in progress and will be updated with further information.

### CODE REVIEW

**Comment by 123marvin123** [comment]
image

(Just a random ascii image)

**Comment by grtcdr** [comment]
Looking better and better  :smile:

**Comment by 123marvin123** [comment]
image

**Comment by grtcdr** [comment]
Seems like the newer macOS terminal implementation solves #47 third question.

**Comment by grtcdr** [comment]
We should have a separate ASCII file, from which the appropriate ASCII art should be picked for a specific operating system or GNU/Linux distribution, or a fallback Linux (penguin) ASCII for all the distributions whose ASCII art is not implemented yet.

**Comment by 123marvin123** [comment]
image

How do you like the new "macchina --doctor" feature, which displays detailed information on why a specific readout might or might not resulted in a correct value?

**Comment by 123marvin123** [comment]
> We should have a separate ASCII file, from which the appropriate ASCII art should be picked for a specific operating system or GNU/Linux distribution, or a fallback Linux (penguin) ASCII for all the distributions whose ASCII art is not implemented yet.

Yes, definitely. The current penguin is just there for testing.

**Comment by grtcdr** [comment]
> image
> 
> How do you like the new "macchina --doctor" feature, which displays detailed information on why a specific readout might or might not resulted in a correct value?

This is a brilliant idea, but it's not yet available for Linux, so I can't test it..

**Comment by 123marvin123** [comment]
> > image
> > How do you like the new "macchina --doctor" feature, which displays detailed information on why a specific readout might or might not resulted in a correct value?
> 
> This is a brilliant idea, but it's not yet available for Linux, so I can't test it..

It's not yet ready for linux :) I'll push it to the branch but the build will fail on linux and windows. I'll fix it soon after the push.

**Comment by grtcdr** [comment]
Looks like it could replace --debug, because --debug isn't this verbose, colorful or comprehensive.

**Comment by 123marvin123** [comment]
Btw: I also implemented a method of displaying multiple package readouts. If you have two package managers installed, it will display both readings and add the corresponding name behind the readout.

image

**Comment by 123marvin123** [comment]
> Looks like it could replace --debug, because --debug isn't this verbose, colorful or comprehensive.

I actually removed the --debug switch and change it into --doctor :)

**Comment by grtcdr** [comment]
> Btw: I also implemented a method of displaying multiple package readouts. If you have two package managers installed, it will display both readings and add the corresponding name behind the readout.
> 
> image

Awesome! satisfying issue #46 

`--doctor` sounds better than `--debug` :man_health_worker:

**Comment by 123marvin123** [comment]
@grtcdr We'll have to update the README.md files too, after we did our UI revamp.

**Comment by grtcdr** [comment]
> @grtcdr We'll have to update the README.md files too, after we did our UI revamp.

We definitely should, a screenshot for classic/TUI in the README, and another for every supported platform in the Wiki

**Comment by 123marvin123** [comment]
Now we just need to implement some platform-specific ascii art :)

**Pull request merged**
