### PR TITLE
Add package count for Fedora

### PR DESCRIPTION
**Pull request by laurentlbm**
Title says it all.

### CODE REVIEW

**Comment by grtcdr** [comment]
I'm currently looking for ways to do this, but without querying **dnf**, because it's a mindblowingly slow package manager.
Do you have any suggestions?

**Comment by laurentlbm** [comment]
rpm is still included in Fedora and is more low-level than dnf, though I didn't benchmark it...

**Comment by grtcdr** [comment]
> rpm is still included in Fedora and is more low-level than dnf, though I didn't benchmark it...

Could you do that for me?
Here's how I benchmark this command:
hyperfine -w 5 -m 20 "rpm -qa | wc -l" --export-markdown _file_

After that, just provide the content of the new _file_.

**Comment by laurentlbm** [comment]
Ok, it's awful. I'll look for alternatives.
```
| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `rpm -qa \| wc -l` | 555.5 ± 3.0 | 548.9 | 559.4 | 1.00 |
```

**Comment by grtcdr** [comment]
> Ok, it's awful. I'll look for alternatives.
> Command 	Mean [ms] 	Min [ms] 	Max [ms] 	Relative
> `rpm -qa | wc -l` 	555.5 ± 3.0 	548.9 	559.4 	1.00

Yeah, I guess they're both unbearably slow.
An alternative solution would be to look into the directory that rpm/dnf places your installed packages in.

**Comment by laurentlbm** [comment]
Found that rpm keeps its data in a sqlite file. It's a fast alternative. Did a quick benchmark when using a command. The results are very good. Next step would be to benchmark in rust.

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|                                 | `sqlite3 /var/lib/rpm/rpmdb.sqlite 'select count(*) from Installtid;'` | 1.7 ± 0.4 | 1.2 | 7.1 | 1.00 |

**Comment by grtcdr** [comment]
> Found that rpm keeps its data in a sqlite file. Did a quick benchmark when using a command. The results are very good. Next step would be to benchmark in rust.

That's awesome, that's at least a hundred times faster than querying rpm or dnf, but I have one question:
Is the host guaranteed to have sqlite3 installed, does fedora automatically install it?

**Comment by laurentlbm** [comment]
I was thinking of using [rusqlite](https://github.com./rusqlite/rusqlite), which can bundle SQLite's C API

**Comment by laurentlbm** [comment]
Actually, Fedora might already include the C API, since RPM needs to query sqlite...

**Comment by grtcdr** [comment]
Hey, any new progress?

**Comment by laurentlbm** [comment]
Didn't have much time to work on it, so I just got it working. It doesn't affect performance anymore!

Please review the code, I went fast.

**Comment by grtcdr** [comment]
Looks good to me, but my only gripe with approach this is the amount of dependencies we're pulling just to support package count for the few distributions that utilize RPM or DNF.

**Comment by laurentlbm** [comment]
I fully agree! I was thinking that it could be turned on at build-time using features.
Also, I see some crates have build.rs script, so I think it's possible to turn on the rpm feature automatically when building on a system with rpm.

The downside is that if binaries are distributed, we need a separate one for rpm-based distributions.

**Comment by grtcdr** [comment]
> I fully agree! I was thinking that it could be turned on at build-time using features.
> Also, I see some crates have build.rs script, so I think it's possible to turn on the rpm feature automatically when building on a system with rpm.
> 
> The downside is that if binaries are distributed, we need a separate one for rpm-based distributions.

We might get away with running sqlite for now.
On KDE for example, a lot of packages depend on it so I can't uninstall it, and it might just be the same for RHEL-based distributions.

**Comment by laurentlbm** [comment]
I used `rusqlite` instead of calling the `sqlite` command. The command was unfortunately not installed by default on my Fedora installation.

**Comment by laurentlbm** [comment]
The addition of `rusqlite` (with its embedded sqlite C lib) makes an unacceptable increase in binary size:
- Without `rusqlite`: 2.6 MB (2,644,144 bytes)
- With `rusqlite`: 4.4 MB (4,358,192 bytes)

**Comment by laurentlbm** [comment]
Switched to crate `sqlite` instead of `rusqlite`, the binary increases less in size.

For comparison, I built `macchina` (in release mode) on Arch and on Fedora, because they result in very different binaries (I don't know why).

<table>
<tr>
	<td>
	<td>Arch
	<td>Fedora
<tr>
	<td>main
	<td>2.6 MB (2,644,144 bytes)
	<td>5.6 MB (5,641,744 bytes)
<tr>
	<td>with rusqlite
	<td>4.4 MB (4,358,192 bytes) [+ 64.8 %]
	<td>7.3 MB (7,335,840 bytes) [+ 30.0 %]
<tr>
	<td>with sqlite
	<td>2.7 MB (2,653,336 bytes) [+ 0.35 %]
	<td>6.8 MB (6,780,592 bytes) [+ 20.2 %]
</table>

**Comment by grtcdr** [comment]
Thanks for the detailed statistics!
Do they both produce the same output?

**Comment by laurentlbm** [comment]
Well, no, since Arch doesn't use RPMs! 😁 They both compile the same code with the same dependencies though.

**Comment by grtcdr** [comment]
> Well, no, since Arch doesn't use RPMs! grin They both compile the same code with the same dependencies though.

No I mean, do they both produce correct output for package count on Fedora?

**Comment by laurentlbm** [comment]
> No I mean, do they both produce correct output for package count on Fedora?

The binary built on Arch doesn't run at all on Fedora, it isn't linked to the same system libraries:
```
./macchina: /lib64/libc.so.6: version 'GLIBC_2.33' not found (required by ./macchina)
```

**Comment by grtcdr** [comment]
> The binary built on Arch doesn't run at all on Fedora, it isn't linked to the same system libraries:
> 
> ```
> ./macchina: /lib64/libc.so.6: version 'GLIBC_2.33' not found (required by ./macchina)
> ```

I'm not following, what are you talking about exactly?

I was asking whether using `sqlite` yields correct package count information..

**Comment by laurentlbm** [comment]
I misunderstood, sorry I'm very tired. Yes, they both output the correct number of packages.

**Comment by grtcdr** [comment]
> I misunderstood, sorry I'm very tired. Yes, they both output the correct number of packages.

Cool, thanks for being patient with me :smile:

**Pull request merged**
