### PR TITLE
Windows Support

### PR DESCRIPTION
**Pull request by 123marvin123**
This PR will add basic Windows support for Macchina.

image

**Work in progress, do not merge yet.**

### CODE REVIEW

**Comment by 123marvin123** [comment]
image

neofetch on Windows has some serious performance issues lol. Running it outside the benchmark confirms the slowness.

**Comment by grtcdr** [comment]
Stuck at uni right now, I'll try and debug with you as soon as I get home :smile:

**Comment by grtcdr** [comment]
This ended up being merged when accepting the `macos` support PR. Oops!

**Comment by 123marvin123** [comment]
> This ended up being merged when accepting the `macos` support PR, because `windows` branch was merged to `macos` branch.

Yea, I accidentally pulled the changes into my macos branch today, but it’s not a big deal.

**Comment by grtcdr** [comment]
Alrighty then, before I forget, I'd like for you to add __macOS__ benchmarks in the "Benchmarks" section of both README files.

**Pull request merged**
